env:
  RCLONECONFIG_DRIVE: ""
  TG_TOKEN: ""
  TG_CHAT_ID: ""
  WORKDIR: "/tmp"
  EMAIL: ""
  CIRRUS_CLONE_DEPTH: "1"
  credentials: ""

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'IQ-7'
  timeout_in: 120m
  container:
    image: zacky46/home:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - git config --global user.name "IQ-7"
     - git config --global user.email "iq7.dev@gmail.com"
     - echo "$credentials" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
